services:
  - type: web
    name: jb-strapi
    env: node
    plan: starter plus
    buildCommand: yarn install && yarn build
    startCommand: yarn start
   # healthCheckPath: /_health
    disk:
      name: strapi-uploads
      mountPath: /opt/render/project/src/public/uploads
      sizeGB: 1
    envVars:
      - key: NODE_VERSION
        value: ~14.19.3
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: strapi
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true
      - key: APP_KEYS
        generateValue: true

databases:
  - name: strapi
    plan: starter